### ISSUE TITLE
CircularBuffer, i have some question

### ISSUE THREAD

**Issue by craigtao** [sawickiap/RegScript2#1]
http://www.asawicki.info/news_1468_circular_buffer_of_raw_binary_data_in_c.html?x=viewnews&id=1468

thanks for your shared, i think there some problems,multi threads  used CircularBuffer,variable 'size_' unsafe,
and, 
code snippet:
size_t bytes_to_write = std::min(bytes, capacity - size_);

some data will lost, can't write into buffer_

it's right？

**Comment by craigtao** [comment]
i think, you can reference the idea of  linux kfifo, 

god bless you!

**Comment by sawickiap** [comment]
You are right, thank for point pointing this out. This code was not intended to be used in multithreaded manner. Interesting read:
https://www.snellman.net/blog/archive/2016-12-13-ring-buffers/

**Comment by craigtao** [comment]
ok,  thank you reply me, i'm come from china, english is not good, sorry about that,
i'm so happy, you can understand what i said.

i will read https://www.snellman.net/blog/archive/2016-12-13-ring-buffers/

thank you, god bless you!
